# Generated by Django 6.0.1 on 2026-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField()),
                ('tipo_error', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('metodo_http', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_cliente', models.GenericIPAddressField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
