# Generated by Django 6.0.1 on 2026-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='ip_cliente',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
