# Generated by Django 6.0.1 on 2026-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_reports', '0002_alter_errorreport_ip_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='tipo_error',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='titulo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
