# Generated by Django 6.0.1 on 2026-02-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tel',
            field=models.CharField(default='', max_length=12),
        ),
    ]
