# Generated by Django 6.0.1 on 2026-02-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='', max_length=70),
        ),
    ]
